# Generated by Django 5.2.5 on 2025-08-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='primer_nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ultima_sesion',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil de Nacimiento'), ('PS', 'Pasaporte')], max_length=2),
        ),
    ]
