# Generated by Django 5.2.5 on 2025-08-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_remove_usuario_activo_remove_usuario_primer_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='fecha_nacimiento',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='numero_documento',
            new_name='document_number',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='tipo_documento',
            new_name='document_type',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='segundo_apellido',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='telefono',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='rol',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='segundo_nombre',
            new_name='second_surname',
        ),
    ]
