# Generated by Django 5.2.5 on 2025-08-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autenticacion", "0003_rename_fecha_nacimiento_usuario_birth_date_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(
                fields=["username"], name="autenticaci_usernam_61a882_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(
                fields=["document_number"], name="autenticaci_documen_ec34e1_idx"
            ),
        ),
    ]
