# Generated by Django 5.2.5 on 2025-08-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autenticacion", "0004_usuario_autenticaci_usernam_61a882_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="phone_prefix",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
