# Generated by Django 5.2.5 on 2025-08-21 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=255)),
                ('segundo_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('primer_apellido', models.CharField(max_length=255)),
                ('segundo_apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil de Nacimiento'), ('PS', 'Pasaporte')], max_length=2)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NA', 'No Aplica')], max_length=10)),
                ('prefijo_telefonico', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'indexes': [models.Index(fields=['primer_nombre', 'segundo_nombre', 'primer_apellido', 'segundo_apellido'], name='pacientes_p_primer__603dec_idx'), models.Index(fields=['numero_documento'], name='pacientes_p_numero__485b0f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('prefijo_telefonico', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('relacion_parentesco', models.CharField(max_length=100)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacto_emergencia', to='pacientes.paciente')),
            ],
            options={
                'indexes': [models.Index(fields=['nombre'], name='pacientes_c_nombre_e6ccf9_idx'), models.Index(fields=['telefono'], name='pacientes_c_telefon_9b4423_idx')],
            },
        ),
    ]
