# Generated by Django 5.2.5 on 2025-08-22 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primer_nombre", models.CharField(max_length=255)),
                (
                    "segundo_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("primer_apellido", models.CharField(max_length=255)),
                (
                    "segundo_apellido",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fecha_nacimiento", models.DateField()),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("TI", "Tarjeta de Identidad"),
                            ("RC", "Registro Civil de Nacimiento"),
                            ("PS", "Pasaporte"),
                        ],
                        max_length=2,
                    ),
                ),
                ("numero_documento", models.CharField(max_length=20)),
                (
                    "sexo",
                    models.CharField(
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Femenino"),
                            ("NA", "No Aplica"),
                        ],
                        max_length=10,
                    ),
                ),
                ("prefijo_telefonico", models.CharField(max_length=10)),
                ("telefono", models.CharField(max_length=20)),
                (
                    "regimen_eps",
                    models.CharField(
                        choices=[
                            ("SISBEN", "SISBEN"),
                            ("REGIMEN_CONTRIBUTIVO", "Régimen Contributivo"),
                            ("REGIMEN_SUBSIDIADO", "Régimen Subsidiado"),
                            ("NO_AFILIADO", "No Afiliado"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "eps",
                    models.CharField(
                        choices=[
                            ("COOSALUD", "COOSALUD"),
                            ("NUEVA_EPS", "NUEVA EPS"),
                            ("MUTUAL_SER", "MUTUAL SER"),
                            ("SALUD_MIA", "SALUD MIA"),
                            ("ALIANSALUD", "ALIANSALUD EPS"),
                            ("SALUD_TOTAL", "SALUD TOTAL EPS S.A."),
                            ("SANITAS", "EPS SANITAS"),
                            ("SURA", "EPS SURA"),
                            ("FAMISANAR", "FAMISANAR"),
                            ("SOS", "SERVICIO OCCIDENTAL DE SALUD EPS SOS"),
                            ("COMFENALCO_VALLE", "COMFENALCO VALLE"),
                            ("COMPENSAR", "COMPENSAR EPS"),
                            ("EPM", "EPM - EMPRESAS PUBLICAS DE MEDELLIN"),
                            (
                                "FONDO_PASIVO_FERROCARRILES",
                                "FONDO DE PASIVO SOCIAL DE FERROCARRILES NACIONALES DE COLOMBIA",
                            ),
                            ("CAJACOPI_ATLANTICO", "CAJACOPI ATLANTICO"),
                            ("CAPRESOCA", "CAPRESOCA"),
                            ("COMFACHOCO", "COMFACHOCO"),
                            ("COMFAORIENTE", "COMFAORIENTE"),
                            ("EPS_FAMILIAR", "EPS FAMILIAR DE COLOMBIA"),
                            ("ASMET_SALUD", "ASMET SALUD"),
                            ("EMSSANAR", "EMSSANAR E.S.S."),
                            ("CAPITAL_SALUD", "CAPITAL SALUD EPS-S"),
                            ("SAVIA_SALUD", "SAVIA SALUD EPS"),
                            ("DUSAKAWI", "DUSAKAWI EPSI"),
                            (
                                "ASOCIACION_INDIGENA_CAUCA",
                                "ASOCIACION INDIGENA DEL CAUCA EPSI",
                            ),
                            ("ANAS_WAYUU", "ANAS WAYUU EPSI"),
                            ("MALLAMAS", "MALLAMAS EPSI"),
                            ("PIJAOS_SALUD", "PIJAOS SALUD EPSI"),
                            ("NO_AFILIADO", "NO AFILIADO"),
                        ],
                        max_length=100,
                    ),
                ),
                ("tiene_seguro_medico", models.BooleanField(default=False)),
                (
                    "nombre_seguro_medico",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sintomas_iniciales", models.TextField()),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "indexes": [
                    models.Index(
                        fields=[
                            "primer_nombre",
                            "segundo_nombre",
                            "primer_apellido",
                            "segundo_apellido",
                        ],
                        name="pacientes_p_primer__603dec_idx",
                    ),
                    models.Index(
                        fields=["numero_documento"],
                        name="pacientes_p_numero__485b0f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContactoEmergencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primer_nombre", models.CharField(max_length=255)),
                (
                    "segundo_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("primer_apellido", models.CharField(max_length=255)),
                (
                    "segundo_apellido",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("prefijo_telefonico", models.CharField(max_length=10)),
                ("telefono", models.CharField(max_length=20)),
                ("relacion_parentesco", models.CharField(max_length=100)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacto_emergencia",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=[
                            "primer_nombre",
                            "segundo_nombre",
                            "primer_apellido",
                            "segundo_apellido",
                        ],
                        name="pacientes_c_primer__a44401_idx",
                    ),
                    models.Index(
                        fields=["telefono"], name="pacientes_c_telefon_9b4423_idx"
                    ),
                ],
            },
        ),
    ]
