# Generated by Django 5.2.6 on 2025-09-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="estado",
            field=models.CharField(
                choices=[
                    ("EN_ESPERA", "En espera"),
                    ("EN_ATENCION", "En atención"),
                    ("ATENDIDO", "Atendido"),
                    ("ABANDONO", "Abandono"),
                ],
                default="EN_ESPERA",
                max_length=20,
            ),
        ),
    ]
