# Generated by Django 5.2.6 on 2025-10-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_add_abandono_state'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['tipo_documento', 'numero_documento'], name='pac_tipo_num_doc_idx'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'numero_documento'), name='unique_documento_per_tipo'),
        ),
    ]
