DOC_CHOICES = [
    ('CC', 'Cédula de Ciudadanía'),
    ('TI', 'Tarjeta de Identidad'),
    ('RC', 'Registro Civil de Nacimiento'),
    ('PS', 'Pasaporte'),
]

ROL_CHOICES = [
    ('admin', 'Administrador'),
    ('estandar', 'Estándar'),
]

SEX_CHOICES = [
    ('M', 'Masculino'),
    ('F', 'Femenino'),
    ('NA', 'No Aplica')
]

EPS_CHOICES = [
    ('COOSALUD', 'COOSALUD'),
    ('NUEVA_EPS', 'NUEVA EPS'),
    ('MUTUAL_SER', 'MUTUAL SER'),
    ('SALUD_MIA', 'SALUD MIA'),
    ('ALIANSALUD', 'ALIANSALUD EPS'),
    ('SALUD_TOTAL', 'SALUD TOTAL EPS S.A.'),
    ('SANITAS', 'EPS SANITAS'),
    ('SURA', 'EPS SURA'),
    ('FAMISANAR', 'FAMISANAR'),
    ('SOS', 'SERVICIO OCCIDENTAL DE SALUD EPS SOS'),
    ('COMFENALCO_VALLE', 'COMFENALCO VALLE'),
    ('COMPENSAR', 'COMPENSAR EPS'),
    ('EPM', 'EPM - EMPRESAS PUBLICAS DE MEDELLIN'),
    ('FONDO_PASIVO_FERROCARRILES', 'FONDO DE PASIVO SOCIAL DE FERROCARRILES NACIONALES DE COLOMBIA'),
    ('CAJACOPI_ATLANTICO', 'CAJACOPI ATLANTICO'),
    ('CAPRESOCA', 'CAPRESOCA'),
    ('COMFACHOCO', 'COMFACHOCO'),
    ('COMFAORIENTE', 'COMFAORIENTE'),
    ('EPS_FAMILIAR', 'EPS FAMILIAR DE COLOMBIA'),
    ('ASMET_SALUD', 'ASMET SALUD'),
    ('EMSSANAR', 'EMSSANAR E.S.S.'),
    ('CAPITAL_SALUD', 'CAPITAL SALUD EPS-S'),
    ('SAVIA_SALUD', 'SAVIA SALUD EPS'),
    ('DUSAKAWI', 'DUSAKAWI EPSI'),
    ('ASOCIACION_INDIGENA_CAUCA', 'ASOCIACION INDIGENA DEL CAUCA EPSI'),
    ('ANAS_WAYUU', 'ANAS WAYUU EPSI'),
    ('MALLAMAS', 'MALLAMAS EPSI'),
    ('PIJAOS_SALUD', 'PIJAOS SALUD EPSI'),
]