# Generated by Django 5.2.6 on 2025-09-29 16:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("texto", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("boolean", "Sí/No"),
                            ("numeric", "Numérico"),
                            ("choice", "Selección única"),
                            ("multi_choice", "Selección múltiple"),
                            ("scale", "Escala"),
                            ("text", "Texto libre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("opciones", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="SesionTriage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("nivel_triage", models.IntegerField(blank=True, null=True)),
                ("completado", models.BooleanField(default=False)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesiones_triage",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Respuesta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("valor", models.JSONField()),
                ("informacion_adicional", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "pregunta_siguiente",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="triage.pregunta",
                    ),
                ),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="triage.sesiontriage",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "unique_together": {("sesion", "pregunta")},
            },
        ),
    ]
