# Generated by Django 5.2.5 on 2025-08-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pregunta",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("boolean", "Sí/No"),
                    ("numeric", "Numérico"),
                    ("choice", "Selección única"),
                    ("multi_choice", "Selección múltiple"),
                    ("scale", "Escala"),
                    ("text", "Texto libre"),
                ],
                max_length=20,
            ),
        ),
    ]
