# Generated by Django 5.2.5 on 2025-08-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triage", "0002_add_multi_choice_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="respuesta",
            name="informacion_adicional",
            field=models.TextField(blank=True, null=True),
        ),
    ]
